### ISSUE TITLE
Recursive inclusion is detected

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#73]
Using the woodstox parser the following error is thrown;

Exception in thread "main" javax.xml.stream.XMLStreamException: Failed to load W3C Schema from 'file:/home/skinkie/Sources/NeTEx/xsd/NeTEx_publication.xsd': {0}; recursive inclusion is detected ( file:/home/skinkie/Sources/NeTEx/xsd/netex_framework/netex_responsibility/netex_responsibility_version.xsd > file:/home/skinkie/Sources/NeTEx/xsd/netex_framework/netex_responsibility/netex_responsibility_version.xsd ); recursive inclusion is detected ( file:/home/skinkie/Sources/NeTEx/xsd/netex_framework/netex_responsibility/netex_responsibility_version.xsd > file:/home/skinkie/Sources/NeTEx/xsd/netex_framework/netex_responsibility/netex_responsibility_version.xsd ); recursive inclusion is detected ( file:/home/skinkie/Sources/NeTEx/xsd/netex_framework/netex_responsibility/netex_responsibility_version.xsd > file:/home/skinkie/Sources/NeTEx/xsd/netex_framework/netex_responsibility/netex_responsibility_version.xsd ); recursive inclusion is detected ( file:/home/skinkie/Sources/NeTEx/xsd/netex_framework/netex_genericFramework/netex_pointAndLinkSequence_version.xsd > file:/home/skinkie/Sources/NeTEx/xsd/netex_framework/netex_genericFramework/netex_pointAndLinkSequence_version.xsd ); recursive inclusion is detected ( file:/home/skinkie/Sources/NeTEx/xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd > file:/home/skinkie/Sources/NeTEx/xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd ); recursive inclusion is detected ( file:/home/skinkie/Sources/NeTEx/xsd/netex_part_2/part2_journeyTimes/netex_flexibleService_version.xsd > file:/home/skinkie/Sources/NeTEx/xsd/netex_part_2/part2_journeyTimes/netex_flexibleService_version.xsd )
	at com.ctc.wstx.msv.W3CSchemaFactory.loadSchema(W3CSchemaFactory.java:77)
	at com.ctc.wstx.msv.BaseSchemaFactory.createSchema(BaseSchemaFactory.java:110)
	at com.ctc.wstx.msv.BaseSchemaFactory.createSchema(BaseSchemaFactory.java:122)

**Comment by nick-knowles** [comment]
Useful to see just where there are cyclic dependencies (Actually I am suprised there are so few <g>).  We should iron out as many of these as possible.  The problem is that, as you can see these are mostly in  kernel framework function where, if we keep to the Transmodel modularisation, there are  inherent cross dependencies.  We can only fix by deviating from this modularisation, either by lumping stuff together or introducing new artefact files.  How important is it to fix? 
 I have proposed fixes for  the flexible service one  at least and will think about the others.

**Comment by skinkie** [comment]
@nick-knowles what is the reason to keep Transmodel modularisation opposed to "XSD normalisation"?

**Comment by ue71603** [comment]
@nick-knowles  as new modes was fixed: What needs to be done there? @Aurige  do we do this in the next work item. I think we should make XSD workable for code genration as intended.

**Comment by Aurige** [comment]
Yes, I agree: can we run the  woodstox parser  again to catch the remaining circular dependencies ?

**Comment by ue71603** [comment]
@skinkie can you run it again eventually?

**Comment by skinkie** [comment]
@ue71603 shall I make something like a jar so you could run it locally too?

```
Exception in thread "main" javax.xml.stream.XMLStreamException: Failed to load W3C Schema from 'file:/home/skinkie/Sources/NeTEx-master/xsd/NeTEx_publication.xsd': {0};
recursive inclusion is detected ( file:/home/skinkie/Sources/NeTEx-master/xsd/netex_framework/netex_responsibility/netex_typeOfValue_version.xsd > file:/home/skinkie/Sources/NeTEx-master/xsd/netex_framework/netex_responsibility/netex_responsibility_version.xsd > file:/home/skinkie/Sources/NeTEx-master/xsd/netex_framework/netex_responsibility/netex_typeOfValue_version.xsd );
recursive inclusion is detected ( file:/home/skinkie/Sources/NeTEx-master/xsd/netex_framework/netex_responsibility/netex_responsibility_version.xsd > file:/home/skinkie/Sources/NeTEx-master/xsd/netex_framework/netex_responsibility/netex_responsibility_version.xsd );
recursive inclusion is detected ( file:/home/skinkie/Sources/NeTEx-master/xsd/netex_framework/netex_responsibility/netex_responsibility_version.xsd > file:/home/skinkie/Sources/NeTEx-master/xsd/netex_framework/netex_responsibility/netex_responsibility_version.xsd );
recursive inclusion is detected ( file:/home/skinkie/Sources/NeTEx-master/xsd/netex_framework/netex_genericFramework/netex_pointAndLinkSequence_version.xsd > file:/home/skinkie/Sources/NeTEx-master/xsd/netex_framework/netex_genericFramework/netex_pointAndLinkSequence_version.xsd );
recursive inclusion is detected ( file:/home/skinkie/Sources/NeTEx-master/xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd > file:/home/skinkie/Sources/NeTEx-master/xsd/netex_part_1/part1_tacticalPlanning/netex_servicePattern_version.xsd );
recursive inclusion is detected ( file:/home/skinkie/Sources/NeTEx-master/xsd/netex_part_3/part3_salesTransactions/netex_salesContract_version.xsd > file:/home/skinkie/Sources/NeTEx-master/xsd/netex_part_3/part3_salesTransactions/netex_salesContract_version.xsd )
```
